package mx.com.ookot.persistence.entity;

// Generated 25/05/2015 01:43:56 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CatInstructores generated by hbm2java
 */
@Entity
@Table(name = "cat_instructores")
public class CatInstructores implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idInstructores;
	private String nombre;
	private String apPaterno;
	private String apMaterno;
	private String numTelefono;
	private String numCelular;
	private String usuario;
	private Status status;

	public CatInstructores() {
	}

	public CatInstructores(int idInstructores, String nombre, String apPaterno,
			String usuario, Status status) {
		this.idInstructores = idInstructores;
		this.nombre = nombre;
		this.apPaterno = apPaterno;
		this.usuario = usuario;
		this.status = status;
	}

	public CatInstructores(int idInstructores, String nombre, String apPaterno,
			String apMaterno, String numTelefono, String numCelular,
			String usuario, Status idStatus) {
		this.idInstructores = idInstructores;
		this.nombre = nombre;
		this.apPaterno = apPaterno;
		this.apMaterno = apMaterno;
		this.numTelefono = numTelefono;
		this.numCelular = numCelular;
		this.usuario = usuario;
		this.status = idStatus;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "IdInstructores", unique = true, nullable = false)
	public int getIdInstructores() {
		return this.idInstructores;
	}

	public void setIdInstructores(int idInstructores) {
		this.idInstructores = idInstructores;
	}

	@Column(name = "Nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "ApPaterno", nullable = false, length = 45)
	public String getApPaterno() {
		return this.apPaterno;
	}

	public void setApPaterno(String apPaterno) {
		this.apPaterno = apPaterno;
	}

	@Column(name = "ApMaterno", nullable = false, length = 45)
	public String getApMaterno() {
		return this.apMaterno;
	}

	public void setApMaterno(String apMaterno) {
		this.apMaterno = apMaterno;
	}

	@Column(name = "NumTelefono", nullable = false, length = 10)
	public String getNumTelefono() {
		return this.numTelefono;
	}

	public void setNumTelefono(String numTelefono) {
		this.numTelefono = numTelefono;
	}

	@Column(name = "NumCelular", nullable = false, length = 10)
	public String getNumCelular() {
		return this.numCelular;
	}

	public void setNumCelular(String numCelular) {
		this.numCelular = numCelular;
	}

	@Column(name = "Usuario", nullable = false, length = 15)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "IdStatus", nullable = false)
	public Status getStatus() {
		return status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}
}
