package mx.com.ookot.persistence.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

// Generated 25/05/2015 01:43:56 PM by Hibernate Tools 4.0.0

/**
 * CatRitmos generated by hbm2java
 */
@Entity
@Table(name="cat_ritmos")
public class CatRitmos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idRitmo;
	private Status status;
	private String nombre;

	public CatRitmos() {
	}

	public CatRitmos(Status status, String nombre) {
		this.status = status;
		this.nombre = nombre;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "IdRitmo", unique = true, nullable = false)
	public Integer getIdRitmo() {
		return this.idRitmo;
	}

	public void setIdRitmo(Integer idRitmo) {
		this.idRitmo = idRitmo;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_status", nullable = false)
	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	@Column(name = "Nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
}
