package mx.com.ookot.persistence.entity;

// Generated 25/05/2015 01:43:56 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClClientes generated by hbm2java
 */
public class ClClientes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idCliente;
	private Usuarios usuarios;
	private Status status;
	private String nombre;
	private String apPaterno;
	private String apMaterno;
	private String rfc;
	private Date fecNacimiento;
	private String numTelefono;
	private String numCelular;
	private String calle;
	private String numeroCasa;
	private String colonia;
	private Integer codPostal;
	private String ciudad;
	private String estado;
	private String pais;
	private Date fechaAlta;
	private Date fechaModificacion;

	public ClClientes() {
	}

	public ClClientes(Usuarios usuarios, Status status, String nombre,
			String apPaterno, Date fechaAlta, Date fechaModificacion) {
		this.usuarios = usuarios;
		this.status = status;
		this.nombre = nombre;
		this.apPaterno = apPaterno;
		this.fechaAlta = fechaAlta;
		this.fechaModificacion = fechaModificacion;
	}

	public ClClientes(Usuarios usuarios, Status status, String nombre,
			String apPaterno, String apMaterno, String rfc, Date fecNacimiento,
			String numTelefono, String numCelular, String calle,
			String numeroCasa, String colonia, Integer codPostal,
			String ciudad, String estado, String pais, Date fechaAlta,
			Date fechaModificacion) {
		this.usuarios = usuarios;
		this.status = status;
		this.nombre = nombre;
		this.apPaterno = apPaterno;
		this.apMaterno = apMaterno;
		this.rfc = rfc;
		this.fecNacimiento = fecNacimiento;
		this.numTelefono = numTelefono;
		this.numCelular = numCelular;
		this.calle = calle;
		this.numeroCasa = numeroCasa;
		this.colonia = colonia;
		this.codPostal = codPostal;
		this.ciudad = ciudad;
		this.estado = estado;
		this.pais = pais;
		this.fechaAlta = fechaAlta;
		this.fechaModificacion = fechaModificacion;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "IdCliente", unique = true, nullable = false)
	public Integer getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(Integer idCliente) {
		this.idCliente = idCliente;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "USUARIO", nullable = false)
	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "IdStatus", nullable = false)
	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	@Column(name = "Nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "ApPaterno", nullable = false, length = 45)
	public String getApPaterno() {
		return this.apPaterno;
	}

	public void setApPaterno(String apPaterno) {
		this.apPaterno = apPaterno;
	}

	@Column(name = "ApMaterno", nullable = false, length = 45)
	public String getApMaterno() {
		return this.apMaterno;
	}

	public void setApMaterno(String apMaterno) {
		this.apMaterno = apMaterno;
	}

	@Column(name = "Rfc", nullable = false, length = 45)
	public String getRfc() {
		return this.rfc;
	}

	public void setRfc(String rfc) {
		this.rfc = rfc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FecNacimiento", nullable = false, length = 19)
	public Date getFecNacimiento() {
		return this.fecNacimiento;
	}

	public void setFecNacimiento(Date fecNacimiento) {
		this.fecNacimiento = fecNacimiento;
	}

	@Column(name = "NumTelefono", nullable = false, length = 10)
	public String getNumTelefono() {
		return this.numTelefono;
	}

	public void setNumTelefono(String numTelefono) {
		this.numTelefono = numTelefono;
	}
	
	@Column(name = "NumCelular", nullable = false, length = 10)
	public String getNumCelular() {
		return this.numCelular;
	}

	public void setNumCelular(String numCelular) {
		this.numCelular = numCelular;
	}

	@Column(name = "Calle", nullable = false, length = 45)
	public String getCalle() {
		return this.calle;
	}

	public void setCalle(String calle) {
		this.calle = calle;
	}

	@Column(name = "NumeroCasa", nullable = false, length = 45)
	public String getNumeroCasa() {
		return this.numeroCasa;
	}

	public void setNumeroCasa(String numeroCasa) {
		this.numeroCasa = numeroCasa;
	}

	@Column(name = "Colonia", nullable = false, length = 45)
	public String getColonia() {
		return this.colonia;
	}

	public void setColonia(String colonia) {
		this.colonia = colonia;
	}

	@Column(name = "CodPostal", nullable = false)
	public Integer getCodPostal() {
		return this.codPostal;
	}

	public void setCodPostal(Integer codPostal) {
		this.codPostal = codPostal;
	}

	@Column(name = "Ciudad", nullable = false, length = 45)
	public String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	@Column(name = "Estado", nullable = false, length = 45)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "Pais", nullable = false, length = 45)
	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaAlta", nullable = false, length = 19)
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaModificacion", nullable = false, length = 19)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

}
