package mx.com.ookot.persistence.entity;

// Generated 25/05/2015 01:43:56 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MenuModuloSeguridad generated by hbm2java
 */
@Entity
@Table(name = "menu_modulo_seguridad")
public class MenuModuloSeguridad implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer idMenu;
	private StatusSeguridad statusSeguridad;
	private String descripcion;
	private Set<ModulosSeguridad> modulosSeguridads = new HashSet<ModulosSeguridad>(0);

	public MenuModuloSeguridad() {
	}

	public MenuModuloSeguridad(StatusSeguridad statusSeguridad,
			String descripcion) {
		this.statusSeguridad = statusSeguridad;
		this.descripcion = descripcion;
	}

	public MenuModuloSeguridad(StatusSeguridad statusSeguridad,
			String descripcion, Set<ModulosSeguridad> modulosSeguridads) {
		this.statusSeguridad = statusSeguridad;
		this.descripcion = descripcion;
		this.modulosSeguridads = modulosSeguridads;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ID_MENU", unique = true, nullable = false)
	public Integer getIdMenu() {
		return this.idMenu;
	}

	public void setIdMenu(Integer idMenu) {
		this.idMenu = idMenu;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_status", nullable = false)
	public StatusSeguridad getStatusSeguridad() {
		return this.statusSeguridad;
	}

	public void setStatusSeguridad(StatusSeguridad statusSeguridad) {
		this.statusSeguridad = statusSeguridad;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 15)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "menuModuloSeguridad")
	public Set<ModulosSeguridad> getModulosSeguridads() {
		return this.modulosSeguridads;
	}

	public void setModulosSeguridads(Set<ModulosSeguridad> modulosSeguridads) {
		this.modulosSeguridads = modulosSeguridads;
	}

}