package mx.com.ookot.persistence.entity;
//Generated 7/10/2014 04:42:04 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
* BcConfiguracion generated by hbm2java
*/
@Entity
@Table(name = "ok_configuracion", uniqueConstraints = @UniqueConstraint(columnNames = "CONFIG_KEY"))
public class OkConfiguracion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idConfiguracion;
	private String configKey;
	private String configValue;

	public OkConfiguracion() {
	}

	public OkConfiguracion(String configKey, String configValue) {
		this.configKey = configKey;
		this.configValue = configValue;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID_CONFIGURACION", unique = true, nullable = false)
	public Integer getIdConfiguracion() {
		return this.idConfiguracion;
	}

	public void setIdConfiguracion(Integer idConfiguracion) {
		this.idConfiguracion = idConfiguracion;
	}

	@Column(name = "CONFIG_KEY", unique = true, nullable = false, length = 100)
	public String getConfigKey() {
		return this.configKey;
	}

	public void setConfigKey(String configKey) {
		this.configKey = configKey;
	}

	@Column(name = "CONFIG_VALUE", nullable = false, length = 500)
	public String getConfigValue() {
		return this.configValue;
	}

	public void setConfigValue(String configValue) {
		this.configValue = configValue;
	}

}
