package mx.com.ookot.persistence.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

// Generated 25/05/2015 01:43:56 PM by Hibernate Tools 4.0.0

/**
 * OpClases generated by hbm2java
 */
@Entity
@Table(name = "cat_instructores")
public class OpClases implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idClases;
	private CatRitmos catRitmos;
	private CatInstructores catInstructores;
	private CatHorarios catHorarios;
	private Status status;
	private String nombre;

	public OpClases() {
	}

	public OpClases(CatRitmos catRitmos, CatInstructores catInstructores,
			CatHorarios catHorarios, Status status, String nombre) {
		this.catRitmos = catRitmos;
		this.catInstructores = catInstructores;
		this.catHorarios = catHorarios;
		this.status = status;
		this.nombre = nombre;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "IdClases", unique = true, nullable = false)
	public Integer getIdClases() {
		return this.idClases;
	}

	public void setIdClases(Integer idClases) {
		this.idClases = idClases;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "IdRitmo", nullable = false)
	public CatRitmos getCatRitmos() {
		return this.catRitmos;
	}

	public void setCatRitmos(CatRitmos catRitmos) {
		this.catRitmos = catRitmos;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "IdInstructores", nullable = false)
	public CatInstructores getCatInstructores() {
		return this.catInstructores;
	}

	public void setCatInstructores(CatInstructores catInstructores) {
		this.catInstructores = catInstructores;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "IdHorario", nullable = false)
	public CatHorarios getCatHorarios() {
		return this.catHorarios;
	}

	public void setCatHorarios(CatHorarios catHorarios) {
		this.catHorarios = catHorarios;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "IdStatus", nullable = false)
	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	@Column(name = "Nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
