package mx.com.ookot.persistence.entity;

// Generated 25/05/2015 01:43:56 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name = "roles", uniqueConstraints = @UniqueConstraint(columnNames = "DESCRIPCION"))
public class Roles implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idRol;
	private StatusSeguridad statusSeguridad;
	private String descripcion;
	private Set<Usuarios> usuarioses = new HashSet<Usuarios>(0);
	private Set<Privilegios> privilegioses = new HashSet<Privilegios>(0);

	public Roles() {
	}

	public Roles(StatusSeguridad statusSeguridad, String descripcion) {
		this.statusSeguridad = statusSeguridad;
		this.descripcion = descripcion;
	}

	public Roles(StatusSeguridad statusSeguridad, String descripcion,
			Set<Usuarios> usuarioses, Set<Privilegios> privilegioses) {
		this.statusSeguridad = statusSeguridad;
		this.descripcion = descripcion;
		this.usuarioses = usuarioses;
		this.privilegioses = privilegioses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ID_ROL", unique = true, nullable = false)
	public Integer getIdRol() {
		return this.idRol;
	}

	public void setIdRol(Integer idRol) {
		this.idRol = idRol;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_STATUS", nullable = false)
	public StatusSeguridad getStatusSeguridad() {
		return this.statusSeguridad;
	}

	public void setStatusSeguridad(StatusSeguridad statusSeguridad) {
		this.statusSeguridad = statusSeguridad;
	}

	@Column(name = "DESCRIPCION", unique = true, nullable = false, length = 45)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "roles")
	public Set<Usuarios> getUsuarioses() {
		return this.usuarioses;
	}

	public void setUsuarioses(Set<Usuarios> usuarioses) {
		this.usuarioses = usuarioses;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "roles")
	public Set<Privilegios> getPrivilegioses() {
		return this.privilegioses;
	}

	public void setPrivilegioses(Set<Privilegios> privilegioses) {
		this.privilegioses = privilegioses;
	}

}