package mx.com.ookot.persistence.entity;

// Generated 25/05/2015 01:43:56 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StatusSeguridad generated by hbm2java
 */
@Entity
@Table(name = "status_seguridad")
public class StatusSeguridad implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idStatus;
	private String descripcion;
	private Set<ModulosSeguridad> modulosSeguridads = new HashSet<ModulosSeguridad>(0);
	private Set<Roles> roleses = new HashSet<Roles>(0);
	private Set<Privilegios> privilegioses = new HashSet<Privilegios>(0);
	private Set<MenuModuloSeguridad> menuModuloSeguridads = new HashSet<MenuModuloSeguridad>(0);
	private Set<Usuarios> usuarioses = new HashSet<Usuarios>(0);

	public StatusSeguridad() {
	}

	public StatusSeguridad(int idStatus, String descripcion) {
		this.idStatus = idStatus;
		this.descripcion = descripcion;
	}

	public StatusSeguridad(int idStatus, String descripcion,
			Set<ModulosSeguridad> modulosSeguridads, Set<Roles> roleses, Set<Privilegios> privilegioses,
			Set<MenuModuloSeguridad> menuModuloSeguridads, Set<Usuarios> usuarioses) {
		this.idStatus = idStatus;
		this.descripcion = descripcion;
		this.modulosSeguridads = modulosSeguridads;
		this.roleses = roleses;
		this.privilegioses = privilegioses;
		this.menuModuloSeguridads = menuModuloSeguridads;
		this.usuarioses = usuarioses;
	}

	@Id
	@Column(name = "ID_STATUS", unique = true, nullable = false)
	public int getIdStatus() {
		return this.idStatus;
	}

	public void setIdStatus(int idStatus) {
		this.idStatus = idStatus;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 45)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "statusSeguridad")
	public Set<ModulosSeguridad> getModulosSeguridads() {
		return this.modulosSeguridads;
	}

	public void setModulosSeguridads(Set<ModulosSeguridad> modulosSeguridads) {
		this.modulosSeguridads = modulosSeguridads;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "statusSeguridad")
	public Set<Roles> getRoleses() {
		return this.roleses;
	}

	public void setRoleses(Set<Roles> roleses) {
		this.roleses = roleses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "statusSeguridad")
	public Set<Privilegios> getPrivilegioses() {
		return this.privilegioses;
	}

	public void setPrivilegioses(Set<Privilegios> privilegioses) {
		this.privilegioses = privilegioses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "statusSeguridad")
	public Set<MenuModuloSeguridad> getMenuModuloSeguridads() {
		return this.menuModuloSeguridads;
	}

	public void setMenuModuloSeguridads(Set<MenuModuloSeguridad> menuModuloSeguridads) {
		this.menuModuloSeguridads = menuModuloSeguridads;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "statusSeguridad")
	public Set<Usuarios> getUsuarioses() {
		return this.usuarioses;
	}

	public void setUsuarioses(Set<Usuarios> usuarioses) {
		this.usuarioses = usuarioses;
	}
	
	public String toString(){
		return this.descripcion;
	}
}
