package mx.com.ookot.persistence.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

// Generated 25/05/2015 01:43:56 PM by Hibernate Tools 4.0.0


/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name = "usuarios", uniqueConstraints = @UniqueConstraint(columnNames = "USUARIO"))
public class Usuarios implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idUsuario;
	private Roles roles;
	private StatusSeguridad statusSeguridad;
	private String nombreComp;
	private String usuario;
	private String password;
	
	public Usuarios() {
	}

	public Usuarios(Roles roles, StatusSeguridad statusSeguridad,
			String nombreComp, String usuario, String password) {
		this.roles = roles;
		this.statusSeguridad = statusSeguridad;
		this.nombreComp = nombreComp;
		this.usuario = usuario;
		this.password = password;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ID_USUARIO", unique = true, nullable = false)
	public Integer getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_ROL", nullable = false)
	public Roles getRoles() {
		return this.roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_STATUS", nullable = false)
	public StatusSeguridad getStatusSeguridad() {
		return this.statusSeguridad;
	}

	public void setStatusSeguridad(StatusSeguridad statusSeguridad) {
		this.statusSeguridad = statusSeguridad;
	}

	@Column(name = "NOMBRE_COMP", nullable = false, length = 150)
	public String getNombreComp() {
		return this.nombreComp;
	}

	public void setNombreComp(String nombreComp) {
		this.nombreComp = nombreComp;
	}

	@Column(name = "USUARIO", unique = true, nullable = false, length = 15)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Column(name = "password", nullable = false, length = 300)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
}